### ISSUE TITLE
Add API to allow read data from a specific `URI`

### ISSUE THREAD

**Issue by lakscastro** [lakscastro/shared-storage#11]
## Details

The most recent Android API's, handle the files as a database of URI's, so we can handle it by adding support for cursor queries, as required by #10, thanks @ankitparmar007.

## Tasks

- [x] Search and add experimental APIs to allow this usecase.
- [x] Add support for `initialUri`.
- [x] Add `copy` API to allow export files.
- [ ] ~Get data dir from a specific app (package id)~ (Not covered by this package).

## Issues

- [x] [Avoid using `listFiles` with large data sets](https://stackoverflow.com/questions/42186820/why-is-documentfile-so-slow-and-what-should-i-use-instead).

## Useful resources

- [How to list files in an android directory](https://stackoverflow.com/questions/8646984/how-to-list-files-in-an-android-directory).
- [Check `query` public method API from `DocumentProvider` class](https://developer.android.com/reference/android/provider/DocumentsProvider#public-methods).
- [THIS](https://stackoverflow.com/questions/41096332/issues-traversing-through-directory-hierarchy-with-android-storage-access-framew) is what I was looking for... maybe. Useful to query a large data set as [we can see here](https://stackoverflow.com/questions/47366768/how-to-list-all-files-inside-a-directory-including-sub-directories-efficiently).
- [Implement initial dir param](https://stackoverflow.com/questions/67552027/android-11-action-open-document-tree-set-initial-uri-to-the-documents-folder).
- Remember: `Tree Document URI` _is **not**_ `Single Document URI`.

**Comment by ankitparmar007** [comment]
@LaksCastro  When You are planning for package update ?

**Comment by LaksCastro** [comment]
When I get some free time on the weekend

**Comment by ankitparmar007** [comment]
Great news that package update will be available on this weekend :)

Also Flutter 2.8.0 • channel stable is live on • [github.com/flutter/flutter.git](https://github.com/flutter/flutter.git)

Make sure package is compatible with the latest version.

Huge Thanks in advance :)

**Comment by LaksCastro** [comment]
Nice!! I did start work right now, later you'll see some updates man and maybe on sunday I'll publish the new release if everything goes fine! thanks for all

**Comment by LaksCastro** [comment]
## Snapshot `13 Dec. 2021`

### News
- Added support for large data sets and removed the API `DocumentFile.listFiles` due to low performance issue
- Refactor of `SAF` API splited into modules to allow safe and easy refactor and new API implementations
- Added support to these `DocumentsContract` and `DocumentFile` APIs:
```kt
const val GET_DOCUMENT_THUMBNAIL = "getDocumentThumbnail"
const val BUILD_DOCUMENT_URI_USING_TREE = "buildDocumentUriUsingTree"
const val BUILD_DOCUMENT_URI = "buildDocumentUri"
const val BUILD_TREE_DOCUMENT_URI = "buildTreeDocumentUri"
```
- Added optional argument `grantWritePermission` to the `openDocumentTree` API

### Missing:
- Support to `copy` a document to another location
- Support to `initialDir` of the `openDocumentTree` API

**Comment by ankitparmar007** [comment]
Definitely a nice progress ! hopefully on next weekend package will be updated with  `Missing APIs` and version code `0.3.0` :)

**Comment by ankitparmar007** [comment]
hey @LaksCastro
Hope You are doing well :)
Btw When are you planning for next package update ?

**Comment by lakscastro** [comment]
All features mentioned in this issue are available on `v0.4.x` except by the last one that doesn't make sense for this package.
