### ISSUE TITLE
Migration to the last SDK version `dart >= 2.16`

### ISSUE THREAD

**Issue by lakscastro** [lakscastro/shared-storage#18]
## Tasks

- [x] Use `lint` package instead `flutter_lints`
- [x] Apply analyzer fixes
- [x] Use Dart SDK `v2.16.x`
