### ISSUE TITLE
Required Tiny patches/updates for `v0.2.0` 

### ISSUE THREAD

**Issue by lakscastro** [lakscastro/shared-storage#7]
## Tasks

Tasks required to release the `v0.2.0` version

- [x] Add script to auto-publish the package when a new commit is pushed to the `release` branch
- [x] Finish all TODO's
- [x] Update documentation `README.md`
- [x] Update `CHANGELOG.md`
